name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Update to the latest LTS version

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npx eslint .  # Use npx to run ESLint

      - name: Clear npm cache
        run: npm cache clean --force

  sast:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t hanzla908/my-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: hanzla908
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your DockerHub password stored as a secret

      - name: Push Docker image
        run: docker push hanzla908/my-app:latest
